/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "SPIS.h"
#include "SPIM.h"
#include "Timer16.h"
#include "USBFS.h"

#endif
