/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
extern void LoadConfig_toastedlightuinousb4( void);
extern void ReloadConfig_toastedlightuinousb4( void);
extern void UnloadConfig_toastedlightuinousb4( void);
extern char Istoastedlightuinousb4Loaded( void);
extern void LoadConfig_serialPassThru( void);
extern void UnloadConfig_serialPassThru( void);
extern char IsserialPassThruLoaded( void);
extern void UnloadConfig_Total( void);
