//*****************************************************************************
//*****************************************************************************
//  FILENAME: Timer16.h
//   Version: 1.1, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 Timer16_EnableInt                       
#pragma fastcall16 Timer16_DisableInt                      
#pragma fastcall16 Timer16_Start                           
#pragma fastcall16 Timer16_Stop                            
#pragma fastcall16 Timer16_SetMode                     
#pragma fastcall16 Timer16_SetPeriod                     


//-------------------------------------------------
// Prototypes of the Timer16 API.
//-------------------------------------------------

extern void Timer16_EnableInt(void);
extern void Timer16_DisableInt(void);
extern void Timer16_Start(void);
extern void Timer16_Stop(void);
extern void Timer16_SetMode(BYTE bMode);
extern void Timer16_SetPeriod(WORD wPeriod);


//--------------------------------------------------
// @INSTANCE_NAME Default Parameters set in the Device Editor
//--------------------------------------------------

#define Timer16_PERIOD                         ( 0x1 )
#define Timer16_MODE                           ( 0x0 )
#define Timer16_CLOCK_SELECT                   ( 0x1 )



// end of file Timer16.h
