; Generated by PSoC Designer 5.0.1127.0
;
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_toastedlightuinousb4_Bank1
export LoadConfigTBL_toastedlightuinousb4_Bank0
export LoadConfigTBL_toastedlightuinousb4_Ordered
export UnloadConfigTBL_toastedlightuinousb4_Bank1
export UnloadConfigTBL_toastedlightuinousb4_Bank0
export ReloadConfigTBL_toastedlightuinousb4_Bank1
export ReloadConfigTBL_toastedlightuinousb4_Bank0
export LoadConfigTBL_serialPassThru_Bank1
export LoadConfigTBL_serialPassThru_Bank0
export UnloadConfigTBL_serialPassThru_Bank1
export UnloadConfigTBL_serialPassThru_Bank0
export UnloadConfigTBL_Total_Bank1
export UnloadConfigTBL_Total_Bank0
AREA lit(rom, rel)
LoadConfigTBL_serialPassThru_Bank0:
;  Instance name SPIS, User Module SPIS
	db		ffh
LoadConfigTBL_serialPassThru_Bank1:
;  Instance name SPIS, User Module SPIS
	db		ffh
UnloadConfigTBL_serialPassThru_Bank0:
;  Instance name SPIS, User Module SPIS
	db		ffh
UnloadConfigTBL_serialPassThru_Bank1:
;  Instance name SPIS, User Module SPIS
	db		ffh

;  Instance name SPIS, User Module SPIS
	db		ffh
LoadConfigTBL_toastedlightuinousb4_Bank0:
;  Instance name SPIM, User Module SPIM
;  Instance name Timer16, User Module Timer16
;  Instance name USBFS, User Module USBFS
;  Global Register values Bank 0
	db		61h, 00h		; AnalogMuxConfig register (AMUX_CFG)
	db		fdh, 00h		; AnalogMuxDAC register (IDAC_D)
	db		a5h, 00h		; CapSense_CountHigh register (CS_CNTH)
	db		a4h, 00h		; CapSense_CountLow register (CS_CNTL)
	db		a0h, 00h		; CapSense_Ctrl0 register (CS_CR0)
	db		a1h, 00h		; CapSense_Ctrl1 register (CS_CR1)
	db		a2h, 00h		; CapSense_Ctrl2 register (CS_CR2)
	db		a3h, 00h		; CapSense_Ctrl3 register (CS_CR3)
	db		a8h, 00h		; CapSense_Slew register (CS_SLEW)
	db		a6h, 00h		; CapSense_Status register (CS_STAT)
	db		a7h, 00h		; CapSense_Timer register (CS_TIMER)
	db		7ch, 33h		; ComparatorLUT register (CMP_LUT)
	db		7ah, 00h		; Comparator_Ctrl0 register (CMP_CR0)
	db		7bh, 04h		; Comparator_Ctrl1 register (CMP_CR1)
	db		79h, 00h		; Comparator_MUX register (CMP_MUX)
	db		36h, 00h		; Endpoint0Control register (EP0_CR)
	db		37h, 00h		; Endpoint0Count register (EP0_CNT)
	db		38h, 00h		; Endpoint0Data0 register (EP0_DR0)
	db		39h, 00h		; Endpoint0Data1 register (EP0_DR1)
	db		3ah, 00h		; Endpoint0Data2 register (EP0_DR2)
	db		3bh, 00h		; Endpoint0Data3 register (EP0_DR3)
	db		3ch, 00h		; Endpoint0Data4 register (EP0_DR4)
	db		3dh, 00h		; Endpoint0Data5 register (EP0_DR5)
	db		3eh, 00h		; Endpoint0Data6 register (EP0_DR6)
	db		3fh, 00h		; Endpoint0Data7 register (EP0_DR7)
	db		40h, 00h		; Endpoint1Count0 register (EP1_CNT)
	db		41h, 00h		; Endpoint1Count1 register (EP1_CNT1)
	db		42h, 00h		; Endpoint2Count0 register (EP2_CNT)
	db		43h, 00h		; Endpoint2Count1 register (EP2_CNT1)
	db		44h, 00h		; Endpoint3Count0 register (EP3_CNT)
	db		45h, 00h		; Endpoint3Count1 register (EP3_CNT1)
	db		46h, 00h		; Endpoint4Count0 register (EP4_CNT)
	db		47h, 00h		; Endpoint4Count1 register (EP4_CNT1)
	db		48h, 00h		; Endpoint5Count0 register (EP5_CNT)
	db		49h, 00h		; Endpoint5Count1 register (EP5_CNT1)
	db		4ah, 00h		; Endpoint6Count0 register (EP6_CNT)
	db		4bh, 00h		; Endpoint6Count1 register (EP6_CNT1)
	db		4ch, 00h		; Endpoint7Count0 register (EP7_CNT)
	db		4dh, 00h		; Endpoint7Count1 register (EP7_CNT1)
	db		4eh, 00h		; Endpoint8Count0 register (EP8_CNT)
	db		4fh, 00h		; Endpoint8Count1 register (EP8_CNT1)
	db		d6h, 00h		; I2CConfig register (I2C_CFG)
	db		d7h, 00h		; I2CStatus_Ctrl register (I2C_SCR)
	db		2bh, 80h		; SpiControl register (SPI_CR)
	db		b0h, 04h		; TimerConfig:0 register (PT0_CFG)
	db		b3h, 00h		; TimerConfig:1 register (PT1_CFG)
	db		b6h, 00h		; TimerConfig:2 register (PT2_CFG)
	db		b2h, 01h		; TimerData0:0 register (PT0_DATA0)
	db		b5h, 00h		; TimerData0:1 register (PT1_DATA0)
	db		b8h, 00h		; TimerData0:2 register (PT2_DATA0)
	db		b1h, 00h		; TimerData1:0 register (PT0_DATA1)
	db		b4h, 00h		; TimerData1:1 register (PT1_DATA1)
	db		b7h, 00h		; TimerData1:2 register (PT2_DATA1)
	db		33h, 00h		; USBControl_0 register (USB_CR0)
	db		34h, 00h		; USBIOControl_0 register (USBIO_CR0)
	db		35h, 00h		; USBIOControl_1 register (USBIO_CR1)
	db		ffh
LoadConfigTBL_toastedlightuinousb4_Bank1:
;  Instance name SPIM, User Module SPIM
;  Instance name Timer16, User Module Timer16
;  Instance name USBFS, User Module USBFS
;  Global Register values Bank 1
	db		54h, 00h		; Endpoint1Control register (EP1_CR)
	db		55h, 00h		; Endpoint2Control register (EP2_CR)
	db		56h, 00h		; Endpoint3Control register (EP3_CR)
	db		57h, 00h		; Endpoint4Control register (EP4_CR)
	db		58h, 00h		; Endpoint5Control register (EP5_CR)
	db		59h, 00h		; Endpoint6Control register (EP6_CR)
	db		5ah, 00h		; Endpoint7Control register (EP7_CR)
	db		5bh, 00h		; Endpoint8Control register (EP8_CR)
	db		dch, 01h		; IOConfig register (IO_CFG)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		ddh, 00h		; OutputOverridePort1 register (OUT_P1)
	db		d8h, 00h		; Port_0_MUXBusCtrl register (MUX_CR0)
	db		d9h, 00h		; Port_1_MUXBusCtrl register (MUX_CR1)
	db		dah, 00h		; Port_2_MUXBusCtrl register (MUX_CR2)
	db		dbh, 00h		; Port_3_MUXBusCtrl register (MUX_CR3)
	db		dfh, 00h		; Port_4_MUXBusCtrl register (MUX_CR4)
	db		29h, 78h		; SpiConfig register (SPI_CFG)
	db		30h, 00h		; USBControl_1 register (USB_CR1)
	db		bdh, 00h		; USB_MISC_CR register (USB_MISC_CR)
	db		ffh
LoadConfigTBL_toastedlightuinousb4_Ordered:
;  Ordered Global Register values
	M8C_SetBank0
	mov	reg[00h], 00h		; Port_0_Data register (PRT0DR)
	M8C_SetBank1
	mov	reg[00h], 00h		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], 9ah		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	mov	reg[04h], 02h		; Port_1_Data register (PRT1DR)
	M8C_SetBank1
	mov	reg[04h], 33h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], b0h		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[05h], 00h		; Port_1_IntEn register (PRT1IE)
	mov	reg[08h], 00h		; Port_2_Data register (PRT2DR)
	M8C_SetBank1
	mov	reg[08h], 08h		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 20h		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	mov	reg[0ch], 00h		; Port_3_Data register (PRT3DR)
	M8C_SetBank1
	mov	reg[0ch], 00h		; Port_3_DriveMode_0 register (PRT3DM0)
	mov	reg[0dh], 00h		; Port_3_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[0dh], 00h		; Port_3_IntEn register (PRT3IE)
	mov	reg[10h], 00h		; Port_4_Data register (PRT3DR)
	M8C_SetBank1
	mov	reg[10h], 00h		; Port_4_DriveMode_0 register (PRT3DM0)
	mov	reg[11h], 00h		; Port_4_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[11h], 00h		; Port_4_IntEn register (PRT3IE)
	M8C_SetBank0
	ret
ReloadConfigTBL_toastedlightuinousb4_Bank0:
;  Instance name SPIM, User Module SPIM
;  Instance name Timer16, User Module Timer16
;  Instance name USBFS, User Module USBFS
	db		ffh
ReloadConfigTBL_toastedlightuinousb4_Bank1:
;  Instance name SPIM, User Module SPIM
;  Instance name Timer16, User Module Timer16
;  Instance name USBFS, User Module USBFS
	db		ffh
UnloadConfigTBL_toastedlightuinousb4_Bank0:
;  Instance name SPIM, User Module SPIM
;  Instance name Timer16, User Module Timer16
;  Instance name USBFS, User Module USBFS
	db		ffh
UnloadConfigTBL_toastedlightuinousb4_Bank1:
;  Instance name SPIM, User Module SPIM
;  Instance name Timer16, User Module Timer16
;  Instance name USBFS, User Module USBFS
	db		ffh

;  Instance name SPIM, User Module SPIM
;  Instance name Timer16, User Module Timer16
;  Instance name USBFS, User Module USBFS
	db		ffh
UnloadConfigTBL_Total_Bank0:
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
	db		ffh
UnloadConfigTBL_Total_Bank1:
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
;  Block 
	db		ffh


; PSoC Configuration file trailer PsocConfig.asm
