; Generated by PSoC Designer 5.0.1127.0
;
;
;  toastedlightuinousb4Dynamic.asm
;
;  Data: 11 June, 2004
;  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
;
;  This file is generated by the Device Editor on Application Generation.
;  It contains functions that can be used to test the state of the 
;  currently active configuration.
;  
;  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
;  Edits to this file will not be preserved.
;
include "m8c.inc"
include "memory.inc"
include "PSoCDynamic.inc"
export Istoastedlightuinousb4Loaded
export _Istoastedlightuinousb4Loaded
export IsserialPassThruLoaded
export _IsserialPassThruLoaded
Istoastedlightuinousb4Loaded:
_Istoastedlightuinousb4Loaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+toastedlightuinousb4_ADDR_OFF], toastedlightuinousb4_BIT
	jz		toastedlightuinousb4IsNotLoaded
	mov		a, 1
toastedlightuinousb4IsNotLoaded:
	ret

IsserialPassThruLoaded:
_IsserialPassThruLoaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+serialPassThru_ADDR_OFF], serialPassThru_BIT
	jz		serialPassThruIsNotLoaded
	mov		a, 1
serialPassThruIsNotLoaded:
	ret

