;  Generated by PSoC Designer 5.1.2309
;
;
;  toastedusbprogrammer1INT.asm
;
;  Data: 29 October, 2001
;  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
;
;  This file is generated by the Device Editor on Application Generation.
;  It contains dispatch code that ensures that interrupt vectors are 
;  serviced by the appropriate ISR depending on the currently active
;  configuration.
;  
;  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
;  Edits to this file will not be preserved.
;
include "PSoCDynamic.inc"
include "m8c.inc"
export	Dispatch_INTERRUPT_6


Dispatch_INTERRUPT_6:
	push	a
	mov		a,0
	tst		[ACTIVE_CONFIG_STATUS+serialPassThru_ADDR_OFF], serialPassThru_BIT
	jnz		Dispatch_INTERRUPT_6_END
	mov		a,4
	tst		[ACTIVE_CONFIG_STATUS+toastedUsbProgrammer1_ADDR_OFF], toastedUsbProgrammer1_BIT
	jnz		Dispatch_INTERRUPT_6_END
	pop		a
	reti
; Stop Code Compressor from breaking table alignment
; The next instruction does not get executed.
	Suspend_CodeCompressor
Dispatch_INTERRUPT_6_END:
	jacc	Dispatch_INTERRUPT_6_TBL
Dispatch_INTERRUPT_6_TBL:
	pop		a
	ljmp	_SPIS_ISR
	pop		a
	ljmp	_SPIM_ISR
; Resume Code Compressor.
; The next instruction does not get executed.
	Resume_CodeCompressor

