/******************************************************************************
*  Generated by PSoC Designer 5.1.2309
******************************************************************************/
extern void LoadConfig_toastedUsbProgrammer1( void);
extern void ReloadConfig_toastedUsbProgrammer1( void);
extern void UnloadConfig_toastedUsbProgrammer1( void);
extern char IstoastedUsbProgrammer1Loaded( void);
extern void LoadConfig_serialPassThru( void);
extern void UnloadConfig_serialPassThru( void);
extern char IsserialPassThruLoaded( void);
extern void UnloadConfig_Total( void);
