/******************************************************************************
*  Generated by PSoC Designer 5.1.2309
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "SPIS.h"
#include "SPIM.h"
#include "Timer16.h"
#include "USBFS.h"

#endif
