/******************************************************************************
*  Generated by PSoC Designer 5.1.2309
******************************************************************************/
#include <m8c.h>
// serialPassThruSPISSCLK address and mask defines
#pragma	ioport	serialPassThruSPISSCLK_Data_ADDR:	0x4
BYTE			serialPassThruSPISSCLK_Data_ADDR;
#pragma	ioport	serialPassThruSPISSCLK_DriveMode_0_ADDR:	0x104
BYTE			serialPassThruSPISSCLK_DriveMode_0_ADDR;
#pragma	ioport	serialPassThruSPISSCLK_DriveMode_1_ADDR:	0x105
BYTE			serialPassThruSPISSCLK_DriveMode_1_ADDR;
#pragma	ioport	serialPassThruSPISSCLK_IntEn_ADDR:	0x5
BYTE			serialPassThruSPISSCLK_IntEn_ADDR;
#define serialPassThruSPISSCLK_MASK 0x1
#pragma	ioport	serialPassThruSPISSCLK_MUXBusCtrl_ADDR:	0x1d9
BYTE			serialPassThruSPISSCLK_MUXBusCtrl_ADDR;
// serialPassThruSPISSCLK Shadow defines
//   serialPassThruSPISSCLK_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define serialPassThruSPISSCLK_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// serialPassThruSPISMOSI address and mask defines
#pragma	ioport	serialPassThruSPISMOSI_Data_ADDR:	0x4
BYTE			serialPassThruSPISMOSI_Data_ADDR;
#pragma	ioport	serialPassThruSPISMOSI_DriveMode_0_ADDR:	0x104
BYTE			serialPassThruSPISMOSI_DriveMode_0_ADDR;
#pragma	ioport	serialPassThruSPISMOSI_DriveMode_1_ADDR:	0x105
BYTE			serialPassThruSPISMOSI_DriveMode_1_ADDR;
#pragma	ioport	serialPassThruSPISMOSI_IntEn_ADDR:	0x5
BYTE			serialPassThruSPISMOSI_IntEn_ADDR;
#define serialPassThruSPISMOSI_MASK 0x2
#pragma	ioport	serialPassThruSPISMOSI_MUXBusCtrl_ADDR:	0x1d9
BYTE			serialPassThruSPISMOSI_MUXBusCtrl_ADDR;
// serialPassThruSPISMOSI Shadow defines
//   serialPassThruSPISMOSI_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define serialPassThruSPISMOSI_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// serialPassThruSPISMISO address and mask defines
#pragma	ioport	serialPassThruSPISMISO_Data_ADDR:	0x4
BYTE			serialPassThruSPISMISO_Data_ADDR;
#pragma	ioport	serialPassThruSPISMISO_DriveMode_0_ADDR:	0x104
BYTE			serialPassThruSPISMISO_DriveMode_0_ADDR;
#pragma	ioport	serialPassThruSPISMISO_DriveMode_1_ADDR:	0x105
BYTE			serialPassThruSPISMISO_DriveMode_1_ADDR;
#pragma	ioport	serialPassThruSPISMISO_IntEn_ADDR:	0x5
BYTE			serialPassThruSPISMISO_IntEn_ADDR;
#define serialPassThruSPISMISO_MASK 0x20
#pragma	ioport	serialPassThruSPISMISO_MUXBusCtrl_ADDR:	0x1d9
BYTE			serialPassThruSPISMISO_MUXBusCtrl_ADDR;
// serialPassThruSPISMISO Shadow defines
//   serialPassThruSPISMISO_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define serialPassThruSPISMISO_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// serialPassThruSPISSS address and mask defines
#pragma	ioport	serialPassThruSPISSS_Data_ADDR:	0x4
BYTE			serialPassThruSPISSS_Data_ADDR;
#pragma	ioport	serialPassThruSPISSS_DriveMode_0_ADDR:	0x104
BYTE			serialPassThruSPISSS_DriveMode_0_ADDR;
#pragma	ioport	serialPassThruSPISSS_DriveMode_1_ADDR:	0x105
BYTE			serialPassThruSPISSS_DriveMode_1_ADDR;
#pragma	ioport	serialPassThruSPISSS_IntEn_ADDR:	0x5
BYTE			serialPassThruSPISSS_IntEn_ADDR;
#define serialPassThruSPISSS_MASK 0x80
#pragma	ioport	serialPassThruSPISSS_MUXBusCtrl_ADDR:	0x1d9
BYTE			serialPassThruSPISSS_MUXBusCtrl_ADDR;
// serialPassThruSPISSS Shadow defines
//   serialPassThruSPISSS_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define serialPassThruSPISSS_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// SPIMSCLK address and mask defines
#pragma	ioport	SPIMSCLK_Data_ADDR:	0x4
BYTE			SPIMSCLK_Data_ADDR;
#pragma	ioport	SPIMSCLK_DriveMode_0_ADDR:	0x104
BYTE			SPIMSCLK_DriveMode_0_ADDR;
#pragma	ioport	SPIMSCLK_DriveMode_1_ADDR:	0x105
BYTE			SPIMSCLK_DriveMode_1_ADDR;
#pragma	ioport	SPIMSCLK_IntEn_ADDR:	0x5
BYTE			SPIMSCLK_IntEn_ADDR;
#define SPIMSCLK_MASK 0x1
#pragma	ioport	SPIMSCLK_MUXBusCtrl_ADDR:	0x1d9
BYTE			SPIMSCLK_MUXBusCtrl_ADDR;
// SPIMSCLK Shadow defines
//   SPIMSCLK_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define SPIMSCLK_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// SPIMMOSI address and mask defines
#pragma	ioport	SPIMMOSI_Data_ADDR:	0x4
BYTE			SPIMMOSI_Data_ADDR;
#pragma	ioport	SPIMMOSI_DriveMode_0_ADDR:	0x104
BYTE			SPIMMOSI_DriveMode_0_ADDR;
#pragma	ioport	SPIMMOSI_DriveMode_1_ADDR:	0x105
BYTE			SPIMMOSI_DriveMode_1_ADDR;
#pragma	ioport	SPIMMOSI_IntEn_ADDR:	0x5
BYTE			SPIMMOSI_IntEn_ADDR;
#define SPIMMOSI_MASK 0x2
#pragma	ioport	SPIMMOSI_MUXBusCtrl_ADDR:	0x1d9
BYTE			SPIMMOSI_MUXBusCtrl_ADDR;
// SPIMMOSI Shadow defines
//   SPIMMOSI_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define SPIMMOSI_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// SPIMMISO address and mask defines
#pragma	ioport	SPIMMISO_Data_ADDR:	0x4
BYTE			SPIMMISO_Data_ADDR;
#pragma	ioport	SPIMMISO_DriveMode_0_ADDR:	0x104
BYTE			SPIMMISO_DriveMode_0_ADDR;
#pragma	ioport	SPIMMISO_DriveMode_1_ADDR:	0x105
BYTE			SPIMMISO_DriveMode_1_ADDR;
#pragma	ioport	SPIMMISO_IntEn_ADDR:	0x5
BYTE			SPIMMISO_IntEn_ADDR;
#define SPIMMISO_MASK 0x20
#pragma	ioport	SPIMMISO_MUXBusCtrl_ADDR:	0x1d9
BYTE			SPIMMISO_MUXBusCtrl_ADDR;
// SPIMMISO Shadow defines
//   SPIMMISO_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define SPIMMISO_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
