;  Generated by PSoC Designer 5.1.2309
;
;
;  toastedusbprogrammer1Dynamic.asm
;
;  Data: 11 June, 2004
;  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
;
;  This file is generated by the Device Editor on Application Generation.
;  It contains functions that can be used to test the state of the 
;  currently active configuration.
;  
;  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
;  Edits to this file will not be preserved.
;
include "m8c.inc"
include "memory.inc"
include "PSoCDynamic.inc"
export IstoastedUsbProgrammer1Loaded
export _IstoastedUsbProgrammer1Loaded
export IsserialPassThruLoaded
export _IsserialPassThruLoaded
IstoastedUsbProgrammer1Loaded:
_IstoastedUsbProgrammer1Loaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+toastedUsbProgrammer1_ADDR_OFF], toastedUsbProgrammer1_BIT
	jz		toastedUsbProgrammer1IsNotLoaded
	mov		a, 1
toastedUsbProgrammer1IsNotLoaded:
	ret

IsserialPassThruLoaded:
_IsserialPassThruLoaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+serialPassThru_ADDR_OFF], serialPassThru_BIT
	jz		serialPassThruIsNotLoaded
	mov		a, 1
serialPassThruIsNotLoaded:
	ret

