//*****************************************************************************
//*****************************************************************************
//  FILENAME: Timer16.h
//   Version: 1.1, Updated on 2011/9/2 at 9:36:55
//  Generated by PSoC Designer 5.1.2309
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Timer16_INCLUDE
#define Timer16_INCLUDE

#include <m8c.h>

#pragma fastcall16 Timer16_EnableInt                       
#pragma fastcall16 Timer16_DisableInt                      
#pragma fastcall16 Timer16_Start                           
#pragma fastcall16 Timer16_Stop                            
#pragma fastcall16 Timer16_SetMode                     
#pragma fastcall16 Timer16_SetPeriod                     


//-------------------------------------------------
// Prototypes of the Timer16 API.
//-------------------------------------------------

extern void Timer16_EnableInt(void);
extern void Timer16_DisableInt(void);
extern void Timer16_Start(void);
extern void Timer16_Stop(void);
extern void Timer16_SetMode(BYTE bMode);
extern void Timer16_SetPeriod(WORD wPeriod);

//--------------------------------------------------
// Constants for Timer16 API's.
//--------------------------------------------------

#define Timer16_INT_MASK                       ( 0x08 )
#define Timer16_INT_CLR_MASK                   ( 0x8 )


//--------------------------------------------------
// @INSTANCE_NAME Default Parameters set in the Device Editor
//--------------------------------------------------

#define Timer16_PERIOD                         ( 0x1 )
#define Timer16_MODE                           ( 0x0 )
#define Timer16_CLOCK_SELECT                   ( 0x1 )

//-------------------------------------------------
// Register Addresses for Timer16
//-------------------------------------------------

#pragma ioport  Timer16_CONFIG_REG: 0x0b0                  // Control register
BYTE            Timer16_CONFIG_REG;
#pragma ioport  Timer16_DATA_0_REG: 0x0b2                  // Input register
BYTE            Timer16_DATA_0_REG;
#pragma ioport  Timer16_DATA_1_REG: 0x0b1                  // Function register
BYTE            Timer16_DATA_1_REG;
#pragma ioport  Timer16_INT_CLR_REG:   0xda                //Interrupt Clear Register
BYTE            Timer16_INT_CLR_REG;
#pragma ioport  Timer16_INT_REG:       0x0e0               //Interrupt Mask Register
BYTE            Timer16_INT_REG;


#endif
// end of file Timer16.h
